[package]
name = "loader-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5"
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1"
thiserror = "1"
ureq = "2.6"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
