[package]
name = "loader-installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.4"
miniserde = "0.1.28"
thiserror = "1.0.38"
ureq = "2.6.2"
